### ISSUE TITLE
How to add our own execution commands?

### ISSUE THREAD

**Issue by iGameChanger** [Eskibear/vscode-maven#1]
Hello,
I work with SpringBoot. I need to understand how to add our own execution commands like ->
` mvn spring-boot:run` , etc to the Maven Projects.

Kindly let me know.

**Comment by Eskibear** [comment]
@gauravdighe1986  Thank you for the advice, I've added custom goals in `v0.0.5`(#2), you can refer to the gif in readme for usage.

**Comment by Eskibear** [comment]
@gauravdighe1986 , I just updated it for better experience, you'd better upgrade it to `v0.0.6`. Any feedback is welcome.
