### ISSUE TITLE
Can't load archetypes when generating from Maven Archetype

### ISSUE THREAD

**Issue by bsaby** [Eskibear/vscode-maven#17]
Build:  artifacts/2/vscode-maven-0.2.1.vsix

![image](https://user-images.githubusercontent.com/22470312/33647909-410a82ae-da92-11e7-850b-a0492ae48c6c.png)

**Comment by Eskibear** [comment]
please verify latest build.

**Comment by bsaby** [comment]
Build used: artifacts/3/vscode-maven-0.3.0.vsix
Windows: work fine.
Mac + Ubuntu: still repro

**Comment by bsaby** [comment]
Build used: artifacts/6/vscode-maven-0.3.0.vsix
Test passed on all OS.
