### ISSUE TITLE
0.3.0 Endgame

### ISSUE THREAD

**Issue by Eskibear** [Eskibear/vscode-maven#21]
## Build
- [x] 12/7 Bump version @Eskibear
- [x] 12/7 Change log (https://github.com/Eskibear/vscode-maven/pull/22) @Eskibear 

## Test
- [x] 12/7 Run test plan https://github.com/Eskibear/vscode-maven/issues/11 @bsaby 
 
## Release
- [x] 12/7 Add tag v0.3.0 @Eskibear
- [x] 12/7 Release to marketplace @Eskibear

**Comment by bsaby** [comment]
# Run test plan
### Configuration

- Windows : Win10
- OSX : Mac Sierra 10.12.4
- Linux: Ubuntu 16.10

## Open bug 

- #27 

## Test result:

Test case | Windows | OSX | Linux
-- | -- | -- | --
Owner | Mona | Sally | Mona
Clean   install | pass | pass | pass
Uninstall | pass | pass | pass
Can list root project in sidebar | Pass | pass | pass
Can   list each root folder in multi-root workspace | Pass | pass | pass
Can   generate Effective POM | Pass | pass | pass
Can   execute common goals | Pass | pass | pass
Can   excute custom goals and perserve command history | Pass | pass | pass
Can   generate projects from Maven Archetype. | Pass | pass | pass 
Can   import all maven projects under specified folder. | #27 | #27 | #27
Can   remove imported projects. | pass | pass | pass
Supported   Shell : PowerShell | Pass | \ | \
Supported   Shell : CMD | Pass | \ | \
Supported   Shell : Git Bash | Pass | \ | \
Supported   Shell : Bash | \ | pass | pass

**Comment by Eskibear** [comment]
Released in: https://marketplace.visualstudio.com/items?itemName=eskibear.vscode-maven
Tag v0.3.0: https://github.com/Eskibear/vscode-maven/releases/tag/v0.3.0
