### ISSUE TITLE
Git bash -> Characters that control color are not recognized

### ISSUE THREAD

**Issue by bsaby** [Eskibear/vscode-maven#24]
git bash: 
![image](https://user-images.githubusercontent.com/22470312/33701835-a6cf1aea-db5b-11e7-8b53-154c93876fa0.png)

![image](https://user-images.githubusercontent.com/22470312/33701715-027ba170-db5b-11e7-9994-fdc5e2904fdd.png)

**Comment by Eskibear** [comment]
low priority, and not supposed to be extension issue.
