### ISSUE TITLE
0.4.0 Endgame

### ISSUE THREAD

**Issue by Eskibear** [Eskibear/vscode-maven#43]
## Build
- [x] 12/27 Bump version #45 
- [x] 12/27 Change log #45 

## Test
- [x] 12/27 Run [Test plan](https://github.com/Eskibear/vscode-maven/wiki/Test-Plan)
 
## Release
- [x] 12/28 Merge code to master branch
- [x] 12/28 Add tag v0.4.0 
- [x] 12/28 Release to marketplace

**Comment by Eskibear** [comment]
await #46

**Comment by Eskibear** [comment]
#46  is merged.

**Comment by bsaby** [comment]
# 12/27 Run Test plan

1. Build: https://vscjavaci.cloudapp.net/job/vscode-maven.vsix/31/Azure/
2. Test plan: https://github.com/Eskibear/vscode-maven/wiki/Test-Plan
3. Test result:

Test case | Windows | OSX | Linux
-- | -- | -- | --
Owner | Mona | Sally | Mona
Clean   install | Pass | pass | pass
Update | Pass | pass | pass
Uninstall | Pass | pass | pass
Maven Project Explorer View - Basic view | Pass | Pass | pass
Maven Project Explorer View - Open   corresponding POM file | Pass | Pass | pass
Maven Project Explorer View - Generate   Effective POM file | Pass | Pass | pass
Maven Project Explorer View - Execute Maven   goals | pass | pass | pass
Maven Project Explorer View - Execute custom   goals | Pass | Pass | pass
Maven   Archetypes - Generate projects from Maven Archetype | Pass | Pass | pass
Maven   Archetypes - Update | Pass | Pass | pass
Multi-root Workspace Support | Pass | Pass | pass
Cross-platform Support | #24 | pass | pass
Non-in-PATH maven executable Support | Pass | pass | pass

**Comment by Eskibear** [comment]
Thanks.
