### ISSUE TITLE
Can't effective pom file using maven wrapper

### ISSUE THREAD

**Issue by bsaby** [Eskibear/vscode-maven#51]
Sample Project: 
https://github.com/spring-projects/spring-petclinic
Under the same setting, "clean" cmd can be executed normally

Windows/OSX:
![image](https://user-images.githubusercontent.com/22470312/34661598-aba0fdac-f485-11e7-98c2-ee9a06cbf02b.png)
Linux: 
![image](https://user-images.githubusercontent.com/22470312/34661582-9bca043c-f485-11e7-9a16-e30b9ee878b6.png)

**Comment by Eskibear** [comment]
@bsaby please verify the latest dev build. BTW, `mvnw` in todo-app is also fixed.

**Comment by bsaby** [comment]
Test passed.
Can effective pom file using maven wrapper on both todo-app and spring-petclinic
Build used: maven0.5.0-dev: 50
